-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2022-04-06 13:03:15 EEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
DROP TABLE class_lease;
DROP TABLE rentals;
DROP TABLE vehicles;
DROP TABLE agencies;
DROP TABLE classes;
DROP TABLE customers;
DROP TABLE leases;

CREATE TABLE agencies (
    id      INTEGER NOT NULL,
    address VARCHAR2(80 CHAR) NOT NULL,
    city    VARCHAR2(40 CHAR) NOT NULL,
    country VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN agencies.city IS
    'There are some cities that have super long names.';

ALTER TABLE agencies ADD CONSTRAINT agencies_pk PRIMARY KEY ( id );

CREATE TABLE class_lease (
    classes_class VARCHAR2(20 CHAR) NOT NULL,
    leases_type   CHAR(1 CHAR) NOT NULL,
    rate          NUMBER(10, 2) DEFAULT 0 NOT NULL
);

ALTER TABLE class_lease ADD CONSTRAINT class_lease_positive CHECK ( rate >= 0 );

COMMENT ON COLUMN class_lease.rate IS
    'Must be >0';

ALTER TABLE class_lease ADD CONSTRAINT class_lease_pk PRIMARY KEY ( classes_class,
                                                                    leases_type );

CREATE TABLE classes (
    class VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE classes ADD CONSTRAINT classes_pk PRIMARY KEY ( class );

CREATE TABLE customers (
    id_num     INTEGER NOT NULL,
    first_name VARCHAR2(20 CHAR) NOT NULL,
    last_name  VARCHAR2(30 CHAR) NOT NULL,
    dob        DATE NOT NULL,
    email      VARCHAR2(50 CHAR),
    phone      VARCHAR2(12 CHAR)
);

COMMENT ON COLUMN customers.id_num IS
    'Passport/ID number are unique';

COMMENT ON COLUMN customers.phone IS
    'Format:
###-###-####';

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY ( id_num );

CREATE TABLE leases (
    type CHAR(1 CHAR) NOT NULL
);

ALTER TABLE leases
    ADD CONSTRAINT s_or_l CHECK ( type IN ( 'l', 's' ) );

COMMENT ON COLUMN leases.type IS
    'Should be s for short or l for long.';

ALTER TABLE leases ADD CONSTRAINT leases_pk PRIMARY KEY ( type );

CREATE TABLE rentals (
    id                   INTEGER NOT NULL,
    start_date           DATE NOT NULL,
    end_date             DATE NOT NULL,
    return_date          DATE,
    insurance            NUMBER(10, 2),
    damages              NUMBER(10, 2),
    cost                 NUMBER(10, 2),
    age_fees             NUMBER(10, 2),
    leases_type          CHAR(1 CHAR) NOT NULL,
    vehicles_id          INTEGER NOT NULL,
    vehicles_agencies_id INTEGER NOT NULL,
    customers_id_num     INTEGER NOT NULL
);

ALTER TABLE rentals ADD CONSTRAINT rentals_ifees_positive CHECK ( insurance >= 0 );

ALTER TABLE rentals ADD CONSTRAINT rentals_dfees_positive CHECK ( damages >= 0 );

ALTER TABLE rentals ADD CONSTRAINT min_cost CHECK ( cost >= 0 );

ALTER TABLE rentals ADD CONSTRAINT rentals_afees_positive CHECK ( age_fees >= 0 );

COMMENT ON COLUMN rentals.insurance IS
    'Must be >0';

COMMENT ON COLUMN rentals.damages IS
    'Must be >0';

COMMENT ON COLUMN rentals.cost IS
    'Must be >0';

COMMENT ON COLUMN rentals.age_fees IS
    '10% of the base cost (age calculated using start date)
Must be >0';

ALTER TABLE rentals
    ADD CONSTRAINT rentals_pk PRIMARY KEY ( id,
                                            vehicles_id,
                                            vehicles_agencies_id,
                                            customers_id_num );

CREATE TABLE vehicles (
    id            INTEGER NOT NULL,
    plate         VARCHAR2(9 CHAR) NOT NULL,
    agencies_id   INTEGER NOT NULL,
    brand         VARCHAR2(20 CHAR) NOT NULL,
    model         VARCHAR2(20) NOT NULL,
    classes_class VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN vehicles.plate IS
    'Format:
####-####';

ALTER TABLE vehicles ADD CONSTRAINT vehicles_pk PRIMARY KEY ( id,
                                                              agencies_id );

ALTER TABLE class_lease
    ADD CONSTRAINT class_lease_classes_fk FOREIGN KEY ( classes_class )
        REFERENCES classes ( class );

ALTER TABLE class_lease
    ADD CONSTRAINT class_lease_leases_fk FOREIGN KEY ( leases_type )
        REFERENCES leases ( type );

ALTER TABLE rentals
    ADD CONSTRAINT rentals_customers_fk FOREIGN KEY ( customers_id_num )
        REFERENCES customers ( id_num );

ALTER TABLE rentals
    ADD CONSTRAINT rentals_leases_fk FOREIGN KEY ( leases_type )
        REFERENCES leases ( type );

ALTER TABLE rentals
    ADD CONSTRAINT rentals_vehicles_fk FOREIGN KEY ( vehicles_id,
                                                     vehicles_agencies_id )
        REFERENCES vehicles ( id,
                              agencies_id );

ALTER TABLE vehicles
    ADD CONSTRAINT vehicles_agencies_fk FOREIGN KEY ( agencies_id )
        REFERENCES agencies ( id );

ALTER TABLE vehicles
    ADD CONSTRAINT vehicles_classes_fk FOREIGN KEY ( classes_class )
        REFERENCES classes ( class );

ALTER TABLE vehicles
    ADD CONSTRAINT unique_plate UNIQUE ( plate );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
